'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18449
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>test1</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>test2</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property SMS_Templates() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("SMS_Templates"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("SMS_Templates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Trial Version")>  _
        Public Property SMS_Account_Name() As String
            Get
                Return CType(Me("SMS_Account_Name"),String)
            End Get
            Set
                Me("SMS_Account_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SMS_Account_Password() As String
            Get
                Return CType(Me("SMS_Account_Password"),String)
            End Get
            Set
                Me("SMS_Account_Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SMS_Account_Type() As String
            Get
                Return CType(Me("SMS_Account_Type"),String)
            End Get
            Set
                Me("SMS_Account_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://121.241.242.114:8080/sendsms?username=")>  _
        Public Property SMS_Account_ProviderURL() As String
            Get
                Return CType(Me("SMS_Account_ProviderURL"),String)
            End Get
            Set
                Me("SMS_Account_ProviderURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Contacts")>  _
        Public Property Customer_Table_Name() As String
            Get
                Return CType(Me("Customer_Table_Name"),String)
            End Get
            Set
                Me("Customer_Table_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Company")>  _
        Public Property Customer_Field_Name() As String
            Get
                Return CType(Me("Customer_Field_Name"),String)
            End Get
            Set
                Me("Customer_Field_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Telephone1")>  _
        Public Property Customer_Contact_Field1() As String
            Get
                Return CType(Me("Customer_Contact_Field1"),String)
            End Get
            Set
                Me("Customer_Contact_Field1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Telephone2")>  _
        Public Property Customer_Contact_Field2() As String
            Get
                Return CType(Me("Customer_Contact_Field2"),String)
            End Get
            Set
                Me("Customer_Contact_Field2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Accounts")>  _
        Public Property Customer_Balance_Table_Name() As String
            Get
                Return CType(Me("Customer_Balance_Table_Name"),String)
            End Get
            Set
                Me("Customer_Balance_Table_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Accountbalance")>  _
        Public Property Customer_Balance_FieldName() As String
            Get
                Return CType(Me("Customer_Balance_FieldName"),String)
            End Get
            Set
                Me("Customer_Balance_FieldName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Representative")>  _
        Public Property Customer_Rep_Field_Name() As String
            Get
                Return CType(Me("Customer_Rep_Field_Name"),String)
            End Get
            Set
                Me("Customer_Rep_Field_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Town")>  _
        Public Property Customer_Location_Field() As String
            Get
                Return CType(Me("Customer_Location_Field"),String)
            End Get
            Set
                Me("Customer_Location_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property IsACCESS() As Boolean
            Get
                Return CType(Me("IsACCESS"),Boolean)
            End Get
            Set
                Me("IsACCESS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsSQLServer() As Boolean
            Get
                Return CType(Me("IsSQLServer"),Boolean)
            End Get
            Set
                Me("IsSQLServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TRIUMPH-PC\SQLEXPRESS")>  _
        Public Property SQLServerName() As String
            Get
                Return CType(Me("SQLServerName"),String)
            End Get
            Set
                Me("SQLServerName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sa")>  _
        Public Property SQLServerUserID() As String
            Get
                Return CType(Me("SQLServerUserID"),String)
            End Get
            Set
                Me("SQLServerUserID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("iM Dummy")>  _
        Public Property MsACCESSFilename() As String
            Get
                Return CType(Me("MsACCESSFilename"),String)
            End Get
            Set
                Me("MsACCESSFilename") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SQLServerUserPassword() As String
            Get
                Return CType(Me("SQLServerUserPassword"),String)
            End Get
            Set
                Me("SQLServerUserPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("swl9")>  _
        Public Property SQL_InitialCatalog() As String
            Get
                Return CType(Me("SQL_InitialCatalog"),String)
            End Get
            Set
                Me("SQL_InitialCatalog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\TRIUMPH\Documents\")>  _
        Public Property MsACCESSFilename_Path() As String
            Get
                Return CType(Me("MsACCESSFilename_Path"),String)
            End Get
            Set
                Me("MsACCESSFilename_Path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property IntegratedSecurity() As Boolean
            Get
                Return CType(Me("IntegratedSecurity"),Boolean)
            End Get
            Set
                Me("IntegratedSecurity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SMS_SenderID() As String
            Get
                Return CType(Me("SMS_SenderID"),String)
            End Get
            Set
                Me("SMS_SenderID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ID2")>  _
        Public Property Customer_Code_Field() As String
            Get
                Return CType(Me("Customer_Code_Field"),String)
            End Get
            Set
                Me("Customer_Code_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=""C:\Users\TRIUMPH\Documents\Intelli"& _ 
            "gent Marketing Schema.accdb""")>  _
        Public ReadOnly Property Intelligent_Marketing_SchemaConnectionString() As String
            Get
                Return CType(Me("Intelligent_Marketing_SchemaConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Email_Account_Name() As String
            Get
                Return CType(Me("Email_Account_Name"),String)
            End Get
            Set
                Me("Email_Account_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Email_Account_Pass() As String
            Get
                Return CType(Me("Email_Account_Pass"),String)
            End Get
            Set
                Me("Email_Account_Pass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public Property SMTP_server_Port() As String
            Get
                Return CType(Me("SMTP_server_Port"),String)
            End Get
            Set
                Me("SMTP_server_Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.mail.yahoo.com")>  _
        Public Property SMTP_server_Server_Host() As String
            Get
                Return CType(Me("SMTP_server_Server_Host"),String)
            End Get
            Set
                Me("SMTP_server_Server_Host") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SMTP_server_Enable_SSL() As Boolean
            Get
                Return CType(Me("SMTP_server_Enable_SSL"),Boolean)
            End Get
            Set
                Me("SMTP_server_Enable_SSL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("kojo_samwoode@yahoo.com")>  _
        Public Property Email_Source() As String
            Get
                Return CType(Me("Email_Source"),String)
            End Get
            Set
                Me("Email_Source") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Email")>  _
        Public Property Customer_Email_Field() As String
            Get
                Return CType(Me("Customer_Email_Field"),String)
            End Get
            Set
                Me("Customer_Email_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Region")>  _
        Public Property Region_Field() As String
            Get
                Return CType(Me("Region_Field"),String)
            End Get
            Set
                Me("Region_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("District")>  _
        Public Property District_Field() As String
            Get
                Return CType(Me("District_Field"),String)
            End Get
            Set
                Me("District_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Voice_SMS_Account_Name() As String
            Get
                Return CType(Me("Voice_SMS_Account_Name"),String)
            End Get
            Set
                Me("Voice_SMS_Account_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Voice_SMS_Account_Password() As String
            Get
                Return CType(Me("Voice_SMS_Account_Password"),String)
            End Get
            Set
                Me("Voice_SMS_Account_Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Voice_SMS_Audio_URL() As String
            Get
                Return CType(Me("Voice_SMS_Audio_URL"),String)
            End Get
            Set
                Me("Voice_SMS_Audio_URL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Voice_SMS_Provider_URL() As String
            Get
                Return CType(Me("Voice_SMS_Provider_URL"),String)
            End Get
            Set
                Me("Voice_SMS_Provider_URL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom_Field1() As String
            Get
                Return CType(Me("Custom_Field1"),String)
            End Get
            Set
                Me("Custom_Field1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom_Field2() As String
            Get
                Return CType(Me("Custom_Field2"),String)
            End Get
            Set
                Me("Custom_Field2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom_Field3() As String
            Get
                Return CType(Me("Custom_Field3"),String)
            End Get
            Set
                Me("Custom_Field3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom_Field4() As String
            Get
                Return CType(Me("Custom_Field4"),String)
            End Get
            Set
                Me("Custom_Field4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom_Field5() As String
            Get
                Return CType(Me("Custom_Field5"),String)
            End Get
            Set
                Me("Custom_Field5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom_Field6() As String
            Get
                Return CType(Me("Custom_Field6"),String)
            End Get
            Set
                Me("Custom_Field6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom_Field7() As String
            Get
                Return CType(Me("Custom_Field7"),String)
            End Get
            Set
                Me("Custom_Field7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom_Field8() As String
            Get
                Return CType(Me("Custom_Field8"),String)
            End Get
            Set
                Me("Custom_Field8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom_Field9() As String
            Get
                Return CType(Me("Custom_Field9"),String)
            End Get
            Set
                Me("Custom_Field9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom_Field10() As String
            Get
                Return CType(Me("Custom_Field10"),String)
            End Get
            Set
                Me("Custom_Field10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IS_PERVASIVE() As Boolean
            Get
                Return CType(Me("IS_PERVASIVE"),Boolean)
            End Get
            Set
                Me("IS_PERVASIVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PSQLSERVERNAME() As String
            Get
                Return CType(Me("PSQLSERVERNAME"),String)
            End Get
            Set
                Me("PSQLSERVERNAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PSQLDatabase_Name() As String
            Get
                Return CType(Me("PSQLDatabase_Name"),String)
            End Get
            Set
                Me("PSQLDatabase_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PSQLDatabase_UserID() As String
            Get
                Return CType(Me("PSQLDatabase_UserID"),String)
            End Get
            Set
                Me("PSQLDatabase_UserID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PSQLDatabase_UserPassword() As String
            Get
                Return CType(Me("PSQLDatabase_UserPassword"),String)
            End Get
            Set
                Me("PSQLDatabase_UserPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Contacts_Table_Name_Pastel() As String
            Get
                Return CType(Me("Contacts_Table_Name_Pastel"),String)
            End Get
            Set
                Me("Contacts_Table_Name_Pastel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Contacts_Field_Name_Pastel() As String
            Get
                Return CType(Me("Contacts_Field_Name_Pastel"),String)
            End Get
            Set
                Me("Contacts_Field_Name_Pastel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Customer_Sales_Archive() As String
            Get
                Return CType(Me("Customer_Sales_Archive"),String)
            End Get
            Set
                Me("Customer_Sales_Archive") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BI_Customer_Accounts_Table() As String
            Get
                Return CType(Me("BI_Customer_Accounts_Table"),String)
            End Get
            Set
                Me("BI_Customer_Accounts_Table") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BI_Customer_Accounts_Name_Field() As String
            Get
                Return CType(Me("BI_Customer_Accounts_Name_Field"),String)
            End Get
            Set
                Me("BI_Customer_Accounts_Name_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BI_Customer_Accounts_Code_Field() As String
            Get
                Return CType(Me("BI_Customer_Accounts_Code_Field"),String)
            End Get
            Set
                Me("BI_Customer_Accounts_Code_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Error_log() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Error_log"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("Error_log") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property iM_Authentication() As Boolean
            Get
                Return CType(Me("iM_Authentication"),Boolean)
            End Get
            Set
                Me("iM_Authentication") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property URL_Input_Webform() As String
            Get
                Return CType(Me("URL_Input_Webform"),String)
            End Get
            Set
                Me("URL_Input_Webform") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property URL_Output_Webform() As String
            Get
                Return CType(Me("URL_Output_Webform"),String)
            End Get
            Set
                Me("URL_Output_Webform") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LicenseKey() As String
            Get
                Return CType(Me("LicenseKey"),String)
            End Get
            Set
                Me("LicenseKey") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.intelligentMarketing.My.MySettings
            Get
                Return Global.intelligentMarketing.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
